/* tslint:disable */
/* eslint-disable */
/**
 * Gateway interaction
 * Explore the functionality of an gateway
 *
 * The version of the OpenAPI document:  - $GITHUB_SHA
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

