name: Checks

on: push

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 'Use NodeJS 16'
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm-

      - name: Install dependencies
        run: npm ci --force
      # use variable to set correct config for bc and test
      - name: prepare for test
        run: mv values.ci.json values.json

      - name: TrustCerts Custom Blockchain
        uses: trustcerts/blockchain-custom-action@main
        with:
          did_id: did:trust:tc:test:id:XLzBJd69tqEgq7oqqdEsHW
          client_name: client
          client_secret: client
          network_size: small

      - uses: trustcerts/nrwl-nx-action@2.1.2
        with:
          targets: install,build,lint
          nxCloud: true
      # - name: Run tests
      # run: npx nx affected --base=last-release --target=test --parallel=false
      # run: npx nx run-many --target=test --parallel=false --skip-nx-cache=true
      - uses: trustcerts/nrwl-nx-action@2.1.2
        with:
          targets: test
          all: 'true'
          parallel: 1
      - name: Upload coverage reports to Codecov with GitHub Action
        uses: codecov/codecov-action@v2
        with:
          directory: ./coverage
